name: Build Docker Image

on:
<<<<<<< HEAD
	push:
	  branches:
	    - main
=======
  push:
    branches:
      - main
>>>>>>> 672e4d9a875b21e79b0f0ae0ecb6467039eea0c8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

<<<<<<< HEAD
	    - name: Build Docker image
	      uses: docker/build-push-action@v3
	      with:
	        context: .
	        push: true
	        tags: agriszirnovs/ubuntu-hello-world:latest
=======
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: yourusername/yourrepo:latest
>>>>>>> 672e4d9a875b21e79b0f0ae0ecb6467039eea0c8
